config/routes.rb
Rails.application.routes.draw do
  root 'mappers#index'
  resources :mappers
end

app/models/mapper.rb
#encoding:utf-8
class Mapper < ActiveRecord::Base
  validates :string1, :string2, presence: true
  validates_format_of :string1, :string2, :with => /\A[0-9a-z]+\z/i
  validates_length_of :string1, :string2, :maximum => 40
end

app/models/mappers/computer.rb
#encoding:utf-8
module Mappers
  class Computer
    # IMPORTANT: The algorithms here are case incenstitive !

    # Converting S1 into an Array of strings, and Sorting S2 in alphabetical order THEN applying the Binary Search algorithm.
    # Worst Case complexity is O(nLogn) = n * Logn ; n is the length of S1, Logn is the complexity of the Binary Search I used to find each element of S1 in S2
    # We need to iterate through S1 (n times), and then for each element of S1 Binary Search it in S2 (Logn) ==> an overall complexity of O(nlogn)
    def self.seek(string1, string2)
      @res = ''
      string1.downcase.split("").each do |c|
        @res += binary_search(string2.downcase.chars.sort.join, c).to_s #usting the .sort method, which by default uses the Quicksort algorithm => O(nLogn) on average case.
      end
      @res.empty? ? 'No matches' : @res
    end

    # Using the Binary search algorithm to search for each element from S1 in S2
    def self.binary_search(string, element)
      high = string.length - 1
      low = 0
      while low <= high do
        current_index = (high + low) / 2
        if element == string[current_index]
          return element
        elsif element < string[current_index]
          high = current_index - 1
        else
          low = current_index + 1
        end
      end
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mappers_controller.rb
#encoding:utf-8
class MappersController < ApplicationController

  before_action :all_mappers, only: [:index, :create, :update, :destroy]
  before_action :set_mappers, only: [:edit, :update, :destroy]
  respond_to :html, :js

  def new
    @mapper = Mapper.new
  end

  def create
    @mapper = Mapper.new(mapper_params)
    @mapper.result = Mappers::Computer.seek(mapper_params[:string1], mapper_params[:string2])
    @mapper.save
    @mapper
  end

  def update
    ActiveRecord::Base.transaction do 
      @mapper.string1 = mapper_params[:string1]
      @mapper.string2 = mapper_params[:string2]
      @mapper.result = Mappers::Computer.seek(mapper_params[:string1], mapper_params[:string2])
      @mapper.save!
    end
    @mapper
  end

  def destroy
    @mapper.destroy
  end

  private

  def all_mappers
    @mappers = Mapper.all
  end

  def set_mappers
    @mapper = Mapper.find(params[:id])
  end

  def mapper_params
    params.require(:mapper).permit(:string1, :string2)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<div class="col-md-5 col-md-offset-1">
  <h1>Zeotap Strings Mappers List</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>Zeoptap Strings Mapper</title>
    <%= stylesheet_link_tag 'application', media: 'all',
      'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row" id="header"><%= render 'layouts/header' %></div>
      <div class="row content"><%= yield %></div>
    </div>
  </body>
</html>

app/views/mappers/_form.html.erb
<%= simple_form_for @mapper, remote: true do |f|   %>
  <%= f.input  :string1, as: :text %>
  <%= f.input  :string2, as: :text %>
  <%= f.button :submit %>
<% end %>

app/views/mappers/_mapper.html.erb
<li class="list-group-item list-group-item-info">
  <%= mapper.string1 %>

  <span class="deadline"><%= mapper.string2 %></span>
  <span class="deadline" style="font-size:20px;"><strong><%= mapper.result %></strong></span>

  <span class="edit">
    <%= link_to edit_mapper_path(mapper), remote: true do %>
      <button class="btn btn-primary btn-xs">Edit</button>
    <% end %>

    
    <%= link_to mapper, remote: true, method: :delete,
        data: { confirm: 'Are you sure?' } do %>
      <button class="btn btn-danger btn-xs">Delete!</button>
    <% end %>
  </span>
</li>

app/views/mappers/create.js.erb
$('#mappers').html("<%= escape_javascript(render @mappers) %>");
$('#mapper-form').slideUp(350);

app/views/mappers/destroy.js.erb
$('#mappers').html("<%= escape_javascript(render @mappers) %>");

app/views/mappers/edit.js.erb
$('#mapper-form').html("<%= escape_javascript(render 'form') %>");
$('#mapper-form').slideDown(350);

<%= render 'datetimepicker' %>

app/views/mappers/index.html.erb
<div class="row">
  <div class="col-md-5 col-md-offset-1">
    <h2>Mappers</h2>
  </div>

  <div class="col-md-2 col-md-offset-4">
    <%= link_to new_mapper_path, remote: true do %>
      <button class="btn btn-default">New</button>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-2" id="mapper-form" style="display:none;"></div>
</div>

<div class="row">
  <div class="col-md-7 col-md-offset-1" id="mappers"><%= render @mappers %></div>
</div>

app/views/mappers/new.js.erb
$('#mapper-form').html("<%= j (render 'form') %>");
$('#mapper-form').slideDown(350);

<%= render 'datetimepicker' %>

app/views/mappers/update.js.erb
$('#mappers').html("<%= escape_javascript(render @mappers) %>");
$('#mapper-form').slideUp(350);